FROM dunglas/frankenphp:1-php8.3

WORKDIR /app

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install --no-dev --optimize-autoloader

ENV SERVER_NAME=:80

EXPOSE 80

CMD ["php-server", "--listen", ":${PORT}", "--root", "public"]